[build]
cmd = "go build -o ./tmp/main cmd/gui/client.go"
bin = "./tmp/main"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
exclude_file = []
stop_on_error = true
log = "stdout"
send_interrupt = false
kill_delay = 0                                   # ms
