version: "2"
linters:
  enable:
    - revive
    - staticcheck
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/dzannotti/anvil
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
