version: "2"

linters:
  enable:
    - revive
    - staticcheck
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - revive
          - goimports
        path: _test\.go
        rules:
          - unused-parameter
    paths:
      - cmd/gui/
      - ^_test\.go

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/dzannotti/anvil
  exclusions:
    generated: lax
    paths:
      - cmd/gui/
      - ^_test\.go
