linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - stylecheck
    - unused
    - whitespace
    - gofmt
    - goimports
    - revive

linters-settings:
  goimports:
    local-prefixes: github.com/dzannotti/anvil

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck