name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [cli, gui]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.4"

      - name: Install GUI dependencies
        if: matrix.target == 'gui'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl1-mesa-dev \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libwayland-dev \
            libwayland-client0 \
            libwayland-cursor0 \
            libwayland-egl1 \
            wayland-protocols \
            libxkbcommon-dev

      - name: Build ${{ matrix.target }}
        run: go build -o bin/${{ matrix.target }} ./cmd/${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-binary
          path: bin/${{ matrix.target }}
