name: Anvil
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Generate coverage report
        run: go test -coverprofile=coverage.out -covermode=atomic ./cmd/cli/... ./internal/...

      - name: Check coverage threshold
        id: coverage
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "total_coverage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "Total coverage: $COVERAGE%"

      - name: Comment PR with coverage
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: coverage
          message: |
            ## Coverage Report
            Total coverage: ${{ steps.coverage.outputs.total_coverage }}%
