name: Anvil
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Cache APT packages
          uses: actions/cache@v3
          with:
            path: |
              /var/cache/apt
              /var/lib/apt/lists
            key: ${{ runner.os }}-apt-${{ hashFiles('**/.github/apt-packages.txt') }}
            restore-keys: |
              ${{ runner.os }}-apt-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo xargs -a apt-packages.txt apt-get install -y
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true

      - name: Generate coverage report
        run: go test -coverprofile=coverage.out -covermode=atomic ./...

      - name: Check coverage threshold
        id: coverage
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "total_coverage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "Total coverage: $COVERAGE%"

      - name: Comment PR with coverage
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: coverage
          message: |
            ## Coverage Report
            Total coverage: ${{ steps.coverage.outputs.total_coverage }}%
