name: Anvil
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Cache apt packages
        id: apt-cache
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/your-dependency-list-file') }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          if [ "${{ steps.apt-cache.outputs.cache-hit }}" != "true" ]; then
            sudo apt-get install -y libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules
          else
            sudo apt-get --fix-broken install
            sudo apt-get install --no-download -y libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules
          fi
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --timeout=5m
