name: Spellcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check spelling
      uses: crate-ci/typos@master
      with:
        files: '.'
        config: .typos.toml
